---
title: "Performing batch prediction"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{automltabularbatch}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r auth, warning=FALSE}
library(googleAuthR)
library(googleCloudVertexAIR)

options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")

gar_auth_service(json_file = Sys.getenv("GAR_SERVICE_JSON"))
```

## Set global arguements

```{r gcva-global-arguements}
projectId <- Sys.getenv("GCVA_DEFAULT_PROJECT_ID")
gcva_region_set(region = "us-central1")
gcva_project_set(projectId = projectId)
```


```{r}
# hard code model that we know has a state = completed for demonstration purposes.
model <- "projects/442003009360/locations/us-central1/models/2734102788232445952"
```

### Make the batch prediction request

#### set constants

```{r}
(bq_source_uri <- sprintf("bq://%s.california_housing.batch_01", projectId))
(bq_destination_prefix <- sprintf("bq://%s.california_housing", projectId))
```

#### execute request

https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.batchPredictionJobs/create


```{r}
batch_prediction_job <- gcva_batch_predict(
  jobDisplayName = "california-housing-batch-01",
  model = model, 
  bigquerySource = bq_source_uri,
  instancesFormat = "bigquery",
  predictionsFormat = "bigquery",
  bigqueryDestinationPrefix = bq_destination_prefix
)

batch_prediction_job
```

```{r}
# show raw JSON body submitted to API for debugging while developing package
# jsonlite::toJSON(batch_prediction_job, pretty = TRUE, auto_unbox = TRUE) 
```

example url: 
https://console.cloud.google.com/vertex-ai/locations/us-central1/batch-predictions/7283609362524798976/properties?project=gc-vertex-ai-r


```{r eval=FALSE, include=FALSE, echo=FALSE, results='hide'}
saveRDS(batch_prediction_job, 
        file = here::here(
          "vignettes",sprintf("batch_prediction_job-response-%s.rds",
                              "california-housing-batch-01")
        )
)
```
```

