---
title: "Datasets"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{datasets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# options(googleAuthR.verbose = 0) # set when debugging
```

# Setup

```{r auth, warning=FALSE}
library(googleAuthR)
library(googleCloudVertexAIR)

options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")

gar_auth_service(json_file = Sys.getenv("GAR_SERVICE_JSON"))
```

# Set global arguements

```{r gcva-global-arguements}
projectId <- Sys.getenv("GCVA_DEFAULT_PROJECT_ID")
gcva_region_set("us-central1")
gcva_project_set(projectId)
```

First, let's set a unique dataset name with a timestamp to avoid confusion:
```{r}
timestamp <- strftime(Sys.time(), "%Y%m%d%H%M%S")
timestamp
```


```{r}
datasetDisplayName <- sprintf("california-housing-%s", timestamp)
datasetDisplayName
```


# List datasets

```{r}
gcva_list_datasets()
```


# Create a dataset

```{r}
dataset <- gcva_create_tabluar_dataset(
  displayName = datasetDisplayName,
  gcsSource = "gs://cloud-samples-data/ai-platform-unified/datasets/tabular/california-housing-tabular-regression.csv")
dataset
```


# List datasets (again)

```{r}
datasets_list <- gcva_list_datasets()
datasets_list
```


# Delete dataset

```{r}
delete_job <- gcva_delete_dataset(displayName = datasetDisplayName)
delete_job
```


# List datasets

```{r}
gcva_list_datasets()
```

