---
title: "Endpoints"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{endpoints}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r warning=FALSE}
library(withr) # for gcloud sdk: https://stackoverflow.com/a/64381848/1812363 
library(glue) 

sh <- function(cmd, args = c(), intern = FALSE) {
  with_path(path.expand("~/google-cloud-sdk/bin/"), {
    if (is.null(args)) {
      cmd <- glue(cmd)
      s <- strsplit(cmd, " ")[[1]]
      cmd <- s[1]
      args <- s[2:length(s)]
    }
    ret <- system2(cmd, args, stdout = TRUE, stderr = TRUE)
    if ("errmsg" %in% attributes(attributes(ret))$names) cat(attr(ret, "errmsg"), "\n")
    if (intern) return(ret) else cat(paste(ret, collapse = "\n"))
  }
  )
}
```



```{r auth, warning=FALSE}
library(googleAuthR)
library(googleCloudVertexAIR)

options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")

gar_auth_service(json_file = Sys.getenv("GAR_SERVICE_JSON"))
```

## Set global arguements

```{r gcva-global-arguements}
projectId <- Sys.getenv("GCVA_DEFAULT_PROJECT_ID")
gcva_region_set(region = "us-central1")
gcva_project_set(projectId = projectId)
```


## Create Endpoint

Doc: [Overview of getting predictions on Vertex AI | Google Cloud](https://cloud.google.com/vertex-ai/docs/predictions/overview#model_deployment)
API: https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.endpoints/create 

```r
endpoint <- gcva_create_endpoint(
    displayName = "CaliforniaHousingEndpoint"
)
endpoint
```


```r
## Dev 
endpoint <- gcva_endpoint(
  endpointName= "projects/442003009360/locations/us-central1/endpoints/1326763089051254784")
endpoint
```

## List Endpoints

```{r}
endpoints <- gcva_list_endpoints()
endpoints
```

## Deploy Model to Endpoint [DEV]

```{r}
# manually set model object (to fasttrack for testing)
model <- gcva_model(model = Sys.getenv("GCVA_TEST_MODEL_NAME_CUSTOM"))
model
```

Doc: https://cloud.google.com/vertex-ai/docs/predictions/get-predictions#api
API: https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.endpoints/deployModel

```r
model_deployed <- gcva_deploy(
  model = model,
  endpoint = endpoint,
  machineType = "n1-standard-4"
)
model_deployed
```

```
2023-03-18 20:45:18> Deploying model to endpoint...
2023-03-18 20:45:28> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:45:38> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:45:48> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:45:58> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:46:08> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:46:19> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:46:29> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:46:39> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:46:49> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:46:59> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:47:09> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:47:19> Model deployment in progress. Waiting 10 seconds before checking operation status.
2023-03-18 20:47:20> Model deployment completed successfully.
$name
[1] "projects/442003009360/locations/us-central1/endpoints/1203107613345054720/operations/4971509788551675904"

$metadata
$metadata$`@type`
[1] "type.googleapis.com/google.cloud.aiplatform.v1.DeployModelOperationMetadata"

$metadata$genericMetadata
$metadata$genericMetadata$createTime
[1] "2023-03-19T00:45:18.085624Z"

$metadata$genericMetadata$updateTime
[1] "2023-03-19T00:47:13.271833Z"



$done
[1] TRUE

$response
$response$`@type`
[1] "type.googleapis.com/google.cloud.aiplatform.v1.DeployModelResponse"

$response$deployedModel
$response$deployedModel$id
[1] "9074185901151617024"



attr(,"class")
[1] "gcva_endpoint"
```

## Predict

### Build sample request

```{r}
data_uri <- "gs://cloud-samples-data/ai-platform-unified/datasets/tabular/california-housing-tabular-regression.csv"
library(jsonlite)
## create example data for prediction request 
data_raw <- read.csv(text=sh("gsutil cat {data_uri}", intern = TRUE))

## convert all to string values to build correct prediction request
data <- as.data.frame(lapply(data_raw, as.character))

## build list of 5 examples/rows only for testing
instances <- list(instances=head(data[, names(data) != "median_house_value"], 5))

## convert to required format of JSON
json_instances <- toJSON(instances, auto_unbox = TRUE, raw = "base64")
json_instances
```



```{r}
gcva_predict(
  endpoint = endpoint,
  instances = json_instances
)
```

## Undeploy

### Single

TODO 

```r
gcva_undeploy(endpoint = endpoint)
```

### All

TODO 

```r
gcva_endpoint_undeploy_all(endpoint = endpoint)
```


## Delete Endpoint

```{r}
# gcva_delete_endpoint(endpoint = endpoints[1,1])
# OR 
gcva_delete_endpoint(endpoint = endpoint)
```

## List Endpoints (again)

to confirm deleted

```{r}
endpoints <- gcva_list_endpoints()
endpoints
```
