---
title: "Gemini"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gemini}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r auth, warning=FALSE}
library(googleAuthR)
library(googleCloudVertexAIR)

options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")

gar_auth_service(json_file = Sys.getenv("GAR_SERVICE_JSON"))
```

## Set global arguements

```{r gcva-global-arguements}
projectId <- Sys.getenv("GCVA_DEFAULT_PROJECT_ID")
gcva_region_set(region = "us-central1")
gcva_project_set(projectId = projectId)
```


## Text 

```{r debug-gar-verbose}
## set verbose log for debugging assistance
# options(googleAuthR.verbose = 0)
```

```{r}
result_gemini <- gcva_gemini_text(
  prompt="Give me ten interview questions for the role of a data scientist related to the R language.",
  modelId="gemini-1.0-pro",
  stream=FALSE)

result_gemini
```


refs:

* https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/overview
* https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini#sample_requests


notes:

2024-02-21 - see potential bug here: https://www.googlecloudcommunity.com/gc/AI-ML/Gemini-s-safety-config-400-error-from-today/m-p/712922/highlight/true
and references: https://cloud.google.com/vertex-ai/docs/generative-ai/multimodal/configure-safety-attributes#gemini-TASK-samples-drest


```{r debug-read-rds}
# request_debug <- readRDS("request_debug.rds")
# request_debug$body_json
```


```{r}
# result_gemini <- gcva_gemini_generate_content(
#   prompt="Give me ten interview questions for the role of a data scientist related to the R language.",
#   modelId="gemini-1.0-pro",
#   stream=FALSE)
# 
# result_gemini
```

