---
title: "Large Language Models"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{large_language_models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r auth, warning=FALSE}
library(googleAuthR)
library(googleCloudVertexAIR)

options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")

gar_auth_service(json_file = Sys.getenv("GAR_SERVICE_JSON"))
```

## Set global arguements

```{r gcva-global-arguements}
projectId <- Sys.getenv("GCVA_DEFAULT_PROJECT_ID")
gcva_region_set(region = "us-central1")
gcva_project_set(projectId = projectId)
```

## Test Prompt - Text Generation 

https://cloud.google.com/vertex-ai/docs/generative-ai/text/test-text-prompts

```{r}
result <- gcva_text_gen_predict(
  prompt="Give me ten interview questions for the role of a Python software engineer.",
  modelId="text-bison",
  rawResponse = TRUE
)

# result$predictions  # prediction  response with safteyAttributes 
result$predictions$content # prediction response only
```
## Test Prompt - Text Chat 

https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text-chat
https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/intro_palm_api.ipynb

```{r}
# gcva_InputOutputTextPair(
#     input_text="How many moons does Mars have?",
#     output_text="The planet Mars has two moons, Phobos and Deimos."
#   )
```



```{r}
# gcva_chat_predict(
#   modelId = "chat-bison@001",
#   context = "My name is Miles. You are an astronomer, knowledgeable about the solar system.",
#   examples = gcva_InputOutputTextPair(
#     input_text="How many moons does Mars have?",
#     output_text="The planet Mars has two moons, Phobos and Deimos."
#   ),
#   messages = "How many planets are there in the solar system?"
# )

```
  
  
## Gemini 

```{r}
# result_gemini <- gcva_gemini(
#   prompt="Give me ten interview questions for the role of a Python software engineer.",
#   modelId="gemini-1.0-pro-001"
# )


```
