json_obj <- structure(list(
  displayName = "TRAINING_PIPELINE_NAME",
  inputDataConfig = structure(list(
    datasetId = "DATASET_ID",
    annotationsFilter = "ANNOTATIONS_FILTER",
    annotationSchemaUri = "ANNOTATION_SCHEMA_URI",
    fractionSplit = structure(list(
      trainingFraction = "TRAINING_FRACTION",
      validationFraction = "VALIDATION_FRACTION",
      testFraction = "TEST_FRACTION"
    ), class = "fractionSplit"),
    filterSplit = structure(list(
      trainingFilter = "TRAINING_FILTER",
      validationFilter = "VALIDATION_FILTER",
      testFilter = "TEST_FILTER"
    ), class = "filterSplit"),
    predefinedSplit = structure(list(
      key = "PREDEFINED_SPLIT_KEY"
    ), class = "predefinedSplit"),
    timestampSplit = structure(list(
      trainingFraction = "TIMESTAMP_TRAINING_FRACTION",
      validationFraction = "TIMESTAMP_VALIDATION_FRACTION",
      testFraction = "TIMESTAMP_TEST_FRACTION",
      key = "TIMESTAMP_SPLIT_KEY"
    ), class = "timestampSplit"),
    gcsDestination = structure(list(
      outputUriPrefix = "OUTPUT_URI_PREFIX"
    ), class = "gcsDestination")
  ), class = "inputDataConfig"),
  trainingTaskDefinition = "gs://google-cloud-aiplatform/schema/trainingjob/definition/custom_task_1.0.0.yaml",
  trainingTaskInputs = structure(list(
    workerPoolSpecs = list(
      structure(list(
        machineSpec = structure(list(
          machineType = "MACHINE_TYPE",
          acceleratorType = "ACCELERATOR_TYPE",
          acceleratorCount = "ACCELERATOR_COUNT"
        ), class = "machineSpec"),
        replicaCount = "REPLICA_COUNT",
        containerSpec = structure(list(
          imageUri = "CUSTOM_CONTAINER_IMAGE_URI",
          command = list("CUSTOM_CONTAINER_COMMAND"),
          args = list("CUSTOM_CONTAINER_ARGS")
        ), class = "containerSpec"),
        pythonPackageSpec = structure(list(
          executorImageUri = "PYTHON_PACKAGE_EXECUTOR_IMAGE_URI",
          packageUris = list("PYTHON_PACKAGE_URIS"),
          pythonModule = "PYTHON_MODULE",
          args = list("PYTHON_PACKAGE_ARGS")
        ), class = "pythonPackageSpec")
      ), class = "workerPoolSpecs")
    ),
    scheduling = structure(list(
      TIMEOUT = "TIMEOUT"
    ), class = "scheduling")
  ), class = "trainingTaskInputs")))
